#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v21
# autospec commit: e36a856
#
# Source0 file verified with key 0x2C8DF587A6D4AAC1 (nicolas.fella@kde.org)
#
Name     : qqc2-desktop-style
Version  : 6.11.0
Release  : 280
URL      : https://download.kde.org/stable/frameworks/6.11/qqc2-desktop-style-6.11.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/6.11/qqc2-desktop-style-6.11.0.tar.xz
Source1  : https://download.kde.org/stable/frameworks/6.11/qqc2-desktop-style-6.11.0.tar.xz.sig
Source2  : 2C8DF587A6D4AAC1.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC0-1.0 GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-2.1 LGPL-3.0
Requires: qqc2-desktop-style-data = %{version}-%{release}
Requires: qqc2-desktop-style-lib = %{version}-%{release}
Requires: qqc2-desktop-style-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : kauth-dev
BuildRequires : kcodecs-dev
BuildRequires : kcoreaddons-dev
BuildRequires : kirigami-dev
BuildRequires : kirigami2-dev
BuildRequires : kwidgetsaddons-dev
BuildRequires : libICE-dev
BuildRequires : libSM-dev
BuildRequires : libX11-dev
BuildRequires : libXScrnSaver-dev
BuildRequires : libXau-dev
BuildRequires : libXcomposite-dev
BuildRequires : libXcursor-dev
BuildRequires : libXdamage-dev
BuildRequires : libXdmcp-dev
BuildRequires : libXext-dev
BuildRequires : libXfixes-dev
BuildRequires : libXft-dev
BuildRequires : libXi-dev
BuildRequires : libXinerama-dev
BuildRequires : libXmu-dev
BuildRequires : libXpm-dev
BuildRequires : libXrandr-dev
BuildRequires : libXrender-dev
BuildRequires : libXres-dev
BuildRequires : libXt-dev
BuildRequires : libXtst-dev
BuildRequires : libXv-dev
BuildRequires : libXxf86vm-dev
BuildRequires : pkg-config
BuildRequires : qt6base-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# QQC2 Desktop Style
This is a style for Qt Quick Controls (also known as QQC2 in Qt5) which uses the application's [QStyle](https://doc.qt.io/qt-6/qstyle.html) to paint the controls in order to give them native look and feel.

%package data
Summary: data components for the qqc2-desktop-style package.
Group: Data

%description data
data components for the qqc2-desktop-style package.


%package dev
Summary: dev components for the qqc2-desktop-style package.
Group: Development
Requires: qqc2-desktop-style-lib = %{version}-%{release}
Requires: qqc2-desktop-style-data = %{version}-%{release}
Provides: qqc2-desktop-style-devel = %{version}-%{release}
Requires: qqc2-desktop-style = %{version}-%{release}

%description dev
dev components for the qqc2-desktop-style package.


%package lib
Summary: lib components for the qqc2-desktop-style package.
Group: Libraries
Requires: qqc2-desktop-style-data = %{version}-%{release}
Requires: qqc2-desktop-style-license = %{version}-%{release}

%description lib
lib components for the qqc2-desktop-style package.


%package license
Summary: license components for the qqc2-desktop-style package.
Group: Default

%description license
license components for the qqc2-desktop-style package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 2C8DF587A6D4AAC1' gpg.status
%setup -q -n qqc2-desktop-style-6.11.0
cd %{_builddir}/qqc2-desktop-style-6.11.0
pushd ..
cp -a qqc2-desktop-style-6.11.0 buildavx2
popd

%build
## build_prepend content
# Make sure the package only builds if kiconthemes and kconfigwidgets have been updated first
sed -i -r -e 's,(KF.?IconThemes \$\{KF.?_DEP_VERSION\})(.*\))$,\1 REQUIRED \2,' CMakeLists.txt || :
sed -i -r -e 's,(KF.?ConfigWidgets \$\{KF.?_DEP_VERSION\})(.*\))$,\1 REQUIRED \2,' CMakeLists.txt || :
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1739572936
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
## build_prepend content
# Make sure the package only builds if kiconthemes and kconfigwidgets have been updated first
sed -i -r -e 's,(KF.?IconThemes \$\{KF.?_DEP_VERSION\})(.*\))$,\1 REQUIRED \2,' CMakeLists.txt || :
sed -i -r -e 's,(KF.?ConfigWidgets \$\{KF.?_DEP_VERSION\})(.*\))$,\1 REQUIRED \2,' CMakeLists.txt || :
## build_prepend end
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1739572936
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qqc2-desktop-style
cp %{_builddir}/qqc2-desktop-style-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/qqc2-desktop-style/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/qqc2-desktop-style-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/qqc2-desktop-style/2a638514c87c4923c0570c55822620fad56f2a33 || :
cp %{_builddir}/qqc2-desktop-style-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/qqc2-desktop-style/e712eadfab0d2357c0f50f599ef35ee0d87534cb || :
cp %{_builddir}/qqc2-desktop-style-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/qqc2-desktop-style/6091db0aead0d90182b93d3c0d09ba93d188f907 || :
cp %{_builddir}/qqc2-desktop-style-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/qqc2-desktop-style/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/qqc2-desktop-style-%{version}/LICENSES/LGPL-2.1-or-later.txt %{buildroot}/usr/share/package-licenses/qqc2-desktop-style/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567 || :
cp %{_builddir}/qqc2-desktop-style-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/qqc2-desktop-style/757b86330df80f81143d5916b3e92b4bcb1b1890 || :
cp %{_builddir}/qqc2-desktop-style-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/qqc2-desktop-style/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/qqc2-desktop-style-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/qqc2-desktop-style/e458941548e0864907e654fa2e192844ae90fc32 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/locale/ar/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/ast/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/ca/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/ca@valencia/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/cs/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/de/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/en_GB/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/eo/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/es/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/eu/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/fi/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/fr/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/gl/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/he/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/hi/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/hu/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/ia/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/it/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/ka/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/ko/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/lv/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/nl/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/nn/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/pl/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/ro/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/ru/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/sa/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/sk/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/sl/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/sv/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/ta/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/tr/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/uk/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/zh_CN/LC_MESSAGES/qqc2desktopstyle_qt.qm
/usr/share/locale/zh_TW/LC_MESSAGES/qqc2desktopstyle_qt.qm

%files dev
%defattr(-,root,root,-)
/usr/lib64/cmake/KF6QQC2DesktopStyle/KF6QQC2DesktopStyleConfig.cmake
/usr/lib64/cmake/KF6QQC2DesktopStyle/KF6QQC2DesktopStyleConfigVersion.cmake

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/qt6/plugins/kf6/kirigami/platform/org.kde.desktop.so
/V3/usr/lib64/qt6/qml/org/kde/desktop/liborg_kde_desktop.so
/V3/usr/lib64/qt6/qml/org/kde/desktop/private/liborg_kde_desktop_private.so
/V3/usr/lib64/qt6/qml/org/kde/qqc2desktopstyle/private/libqqc2desktopstyleplugin.so
/usr/lib64/qt6/plugins/kf6/kirigami/platform/org.kde.desktop.so
/usr/lib64/qt6/qml/org/kde/desktop/BusyIndicator.qml
/usr/lib64/qt6/qml/org/kde/desktop/Button.qml
/usr/lib64/qt6/qml/org/kde/desktop/CheckBox.qml
/usr/lib64/qt6/qml/org/kde/desktop/CheckDelegate.qml
/usr/lib64/qt6/qml/org/kde/desktop/ComboBox.qml
/usr/lib64/qt6/qml/org/kde/desktop/Container.qml
/usr/lib64/qt6/qml/org/kde/desktop/Control.qml
/usr/lib64/qt6/qml/org/kde/desktop/DelayButton.qml
/usr/lib64/qt6/qml/org/kde/desktop/Dial.qml
/usr/lib64/qt6/qml/org/kde/desktop/Dialog.qml
/usr/lib64/qt6/qml/org/kde/desktop/DialogButtonBox.qml
/usr/lib64/qt6/qml/org/kde/desktop/Drawer.qml
/usr/lib64/qt6/qml/org/kde/desktop/Frame.qml
/usr/lib64/qt6/qml/org/kde/desktop/GroupBox.qml
/usr/lib64/qt6/qml/org/kde/desktop/HorizontalHeaderView.qml
/usr/lib64/qt6/qml/org/kde/desktop/ItemDelegate.qml
/usr/lib64/qt6/qml/org/kde/desktop/Label.qml
/usr/lib64/qt6/qml/org/kde/desktop/Menu.qml
/usr/lib64/qt6/qml/org/kde/desktop/MenuBar.qml
/usr/lib64/qt6/qml/org/kde/desktop/MenuBarItem.qml
/usr/lib64/qt6/qml/org/kde/desktop/MenuItem.qml
/usr/lib64/qt6/qml/org/kde/desktop/MenuSeparator.qml
/usr/lib64/qt6/qml/org/kde/desktop/Page.qml
/usr/lib64/qt6/qml/org/kde/desktop/PageIndicator.qml
/usr/lib64/qt6/qml/org/kde/desktop/Pane.qml
/usr/lib64/qt6/qml/org/kde/desktop/Popup.qml
/usr/lib64/qt6/qml/org/kde/desktop/ProgressBar.qml
/usr/lib64/qt6/qml/org/kde/desktop/RadioButton.qml
/usr/lib64/qt6/qml/org/kde/desktop/RadioDelegate.qml
/usr/lib64/qt6/qml/org/kde/desktop/RangeSlider.qml
/usr/lib64/qt6/qml/org/kde/desktop/RoundButton.qml
/usr/lib64/qt6/qml/org/kde/desktop/ScrollBar.qml
/usr/lib64/qt6/qml/org/kde/desktop/ScrollView.qml
/usr/lib64/qt6/qml/org/kde/desktop/Slider.qml
/usr/lib64/qt6/qml/org/kde/desktop/SpinBox.qml
/usr/lib64/qt6/qml/org/kde/desktop/SplitView.qml
/usr/lib64/qt6/qml/org/kde/desktop/StackView.qml
/usr/lib64/qt6/qml/org/kde/desktop/SwipeDelegate.qml
/usr/lib64/qt6/qml/org/kde/desktop/Switch.qml
/usr/lib64/qt6/qml/org/kde/desktop/SwitchDelegate.qml
/usr/lib64/qt6/qml/org/kde/desktop/TabBar.qml
/usr/lib64/qt6/qml/org/kde/desktop/TabButton.qml
/usr/lib64/qt6/qml/org/kde/desktop/TextArea.qml
/usr/lib64/qt6/qml/org/kde/desktop/TextField.qml
/usr/lib64/qt6/qml/org/kde/desktop/ToolBar.qml
/usr/lib64/qt6/qml/org/kde/desktop/ToolButton.qml
/usr/lib64/qt6/qml/org/kde/desktop/ToolSeparator.qml
/usr/lib64/qt6/qml/org/kde/desktop/ToolTip.qml
/usr/lib64/qt6/qml/org/kde/desktop/TreeViewDelegate.qml
/usr/lib64/qt6/qml/org/kde/desktop/VerticalHeaderView.qml
/usr/lib64/qt6/qml/org/kde/desktop/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/desktop/liborg_kde_desktop.so
/usr/lib64/qt6/qml/org/kde/desktop/org_kde_desktop.qmltypes
/usr/lib64/qt6/qml/org/kde/desktop/private/CheckIndicator.qml
/usr/lib64/qt6/qml/org/kde/desktop/private/DefaultListItemBackground.qml
/usr/lib64/qt6/qml/org/kde/desktop/private/DefaultSliderHandle.qml
/usr/lib64/qt6/qml/org/kde/desktop/private/DefaultToolBarBackground.qml
/usr/lib64/qt6/qml/org/kde/desktop/private/FocusRect.qml
/usr/lib64/qt6/qml/org/kde/desktop/private/GlobalSonnetSettings.qml
/usr/lib64/qt6/qml/org/kde/desktop/private/MobileCursor.qml
/usr/lib64/qt6/qml/org/kde/desktop/private/MobileTextActionsToolBar.qml
/usr/lib64/qt6/qml/org/kde/desktop/private/MobileTextActionsToolBarImpl.qml
/usr/lib64/qt6/qml/org/kde/desktop/private/SwitchIndicator.qml
/usr/lib64/qt6/qml/org/kde/desktop/private/TextFieldContextMenu.qml
/usr/lib64/qt6/qml/org/kde/desktop/private/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/desktop/private/liborg_kde_desktop_private.so
/usr/lib64/qt6/qml/org/kde/desktop/private/org_kde_desktop_private.qmltypes
/usr/lib64/qt6/qml/org/kde/desktop/private/qmldir
/usr/lib64/qt6/qml/org/kde/desktop/qmldir
/usr/lib64/qt6/qml/org/kde/qqc2desktopstyle/private/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/qqc2desktopstyle/private/libqqc2desktopstyleplugin.so
/usr/lib64/qt6/qml/org/kde/qqc2desktopstyle/private/qmldir
/usr/lib64/qt6/qml/org/kde/qqc2desktopstyle/private/qqc2desktopstyleplugin.qmltypes

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qqc2-desktop-style/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/qqc2-desktop-style/2a638514c87c4923c0570c55822620fad56f2a33
/usr/share/package-licenses/qqc2-desktop-style/6091db0aead0d90182b93d3c0d09ba93d188f907
/usr/share/package-licenses/qqc2-desktop-style/757b86330df80f81143d5916b3e92b4bcb1b1890
/usr/share/package-licenses/qqc2-desktop-style/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567
/usr/share/package-licenses/qqc2-desktop-style/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/qqc2-desktop-style/e458941548e0864907e654fa2e192844ae90fc32
/usr/share/package-licenses/qqc2-desktop-style/e712eadfab0d2357c0f50f599ef35ee0d87534cb
